### ISSUE TITLE
How can I do both intron count for each sample and gff file that has intron count  with using python scripts of DEXSeq ?

### ISSUE THREAD

**Issue by kaanokay** [roryk/DEXSeq#2]
Hi,
I want to analyze differential intron usage (intron retention) instead of differential exon usage with DEXSeq package. Can you help me about this the analysis? 

Thanks,
Best regards.

**Comment by roryk** [comment]
Hi @kaanokay,

Sorry-- I'm not the author of this package, but AFAIK you can't do that with DEXSeq. There are several other tools that do intron retention differential expression though. We've had a lot of success with IRFinder: https://github.com/williamritchie/IRFinder.
