### ISSUE TITLE
fitted values

### ISSUE THREAD

**Issue by fifdick** [roryk/DEXSeq#3]
Hi,

is it somehow possible to retrieve the fitted counts of a DEXSeq object, i.e. the values used for plotting with plotDEXSeq ?

**Comment by roryk** [comment]
Hi @fifdick,

This is just a fork of the DEXseq repo and I haven't used DEXSeq in a while, so I'm not sure. If you mean the model fits then I'd be surprised if the object doesn't save the fits somewhere in it, if you poke around in the DEXSeq documentation it might describe the object that is returned and how to access them.

**Comment by fifdick** [comment]
oh... i thought i got here  via the bioconductor link. my mistake. sorry. but thanks anyhow

**Comment by roryk** [comment]
No worries!
