### ISSUE TITLE
dexseq_count.py error: ValueError: need more than 4 values to unpack

### ISSUE THREAD

**Issue by CarinaCornejo** [roryk/DEXSeq#4]
Hello everyone,

I am using DEXSeq package and I am getting an error related to the annotation file. 
First I ran the following command without any problem:

`python2.7 /usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_prepare_annotation.py ./Arabidopsis_thaliana.TAIR10.42.gtf ./Arabidopsis_thaliana.TAIR10.42.DEXSeq.gff`

Here is how the output looks:

1       dexseq_prepare_annotation.py    aggregate_gene  3631    5899    .       +       .       gene_id "gene_AT1G01010"
1       dexseq_prepare_annotation.py    exonic_part     3631    3913    .       +       .       transcripts "transcript:AT1G01010.1"; exonic_part_number "001"; gene_id "gene_AT1G01010"
1       dexseq_prepare_annotation.py    exonic_part     3996    4276    .       +       .       transcripts "transcript:AT1G01010.1"; exonic_part_number "002"; gene_id "gene_AT1G01010"
1       dexseq_prepare_annotation.py    exonic_part     4486    4605    .       +       .       transcripts "transcript:AT1G01010.1"; exonic_part_number "003"; gene_id "gene_AT1G01010"
1       dexseq_prepare_annotation.py    exonic_part     4706    5095    .       +       .       transcripts "transcript:AT1G01010.1"; exonic_part_number "004"; gene_id "gene_AT1G01010"

Then I tried the following command:

`python2.7 /usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py -p yes -r name -a 10 -s no -f bam ./S01_mapped_sorted.bam ./S02_mapped_sorted.bam  ./Arabidopsis_thaliana.TAIR10.42.DEXSeq.gff > S01_S02_dexseq_count`

And I got the error:

Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/DEXSeq/python_scripts/dexseq_count.py", line 94, in <module>
    for f in  HTSeq.GFF_Reader( gff_file ):
  File "/usr/lib/python2.7/dist-packages/HTSeq/__init__.py", line 207, in __iter__
    strand, frame, attributeStr ) = line.split( "\t", 8 )
ValueError: need more than 4 values to unpack

Any help will be appreciated.
Thanks!

Carina

**Comment by roryk** [comment]
Hi Carina,

Sorry, this isn't actually the DEXSeq repository, it is just a fork I made a while ago to fix a bug!
